platform :ios, '7.0'

inhibit_all_warnings!

pod 'Reachability', '~> 3.2'
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'Masonry', '~> 0.6.3'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'IQKeyboardManager', '~> 3.3.4'

